name: QA Automation Tests

on:
  workflow_dispatch:  # Ejecucion Mnaual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Chequear el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Ejecutar pruebas con pytest y generar reportes Allure
      - name: Run tests with pytest
        run: |
          pytest -v --alluredir=allure-results

      # 5️⃣ Generar reporte Allure en HTML
      - name: Generate Allure Report
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          ./allure-2.27.0/bin/allure generate allure-results --clean -o allure-report

      # 6️⃣ Subir el reporte a GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
