name: QA Automation Tests

on:
  workflow_dispatch:  # Ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Chequear el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python 3.13.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Configurar y instalar Chrome y ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      # 5️⃣ Ejecutar pruebas con pytest (Selenium en modo headless) y generar reportes Allure
      - name: Run tests with pytest
        run: |
          pytest -v --alluredir=allure-results

      # 6️⃣ Generar reporte Allure en HTML
      - name: Generate Allure Report
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          ./allure-2.27.0/bin/allure generate allure-results --clean -o allure-report

      # 7️⃣ Subir el reporte a GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
